package utilities

import (
	"time"
)

// MetaConfig is the overarching context used by most functions in aeacus.
type MetaConfig struct {
	TeamID     string
	DirPath    string
	Config     ScoringChecks
	Image      ImageData
	Conn       ConnData
	Connection bool
}

// ImageData is the current scoring data for the image. It is able to be
// wiped, removed, etc, on each run without affecting anything else.
type ImageData struct {
	RunningTime time.Time
	Score       int
	ScoredVulns int
	Points      []ScoreItem
	Contribs    int
	Penalties   []ScoreItem
	Detracts    int
	TotalPoints int
}

// ConnData represents the current connectivity state of the image to the
// internet and the scoring server.
type ConnData struct {
	ServerColor   string
	ServerStatus  string
	NetColor      string
	NetStatus     string
	OverallColor  string
	OverallStatus string
}

// ScoreItem is the scoring report representation of a check, containing only
// the message and points associated with it.
type ScoreItem struct {
	Message string
	Points  int
}

// ScoringChecks is a representation of the TOML configuration typically
// specific in scoring.conf.
type ScoringChecks struct {
	Name      string
	Title     string
	User      string
	OS        string
	Remote    string
	Password  string
	Local     bool
	EndDate   string
	NoDestroy bool
	Check     []Check
}

// Check is the smallest unit that can show up on a scoring report. It holds
// all the conditions for a check, and its message and points (autogenerated or
// otherwise).
type Check struct {
	Message      string
	Points       int
	Pass         []Condition
	PassOverride []Condition
	Fail         []Condition
}

// Condition is a single pass/fail condition inside of a check. It supports up
// to four arguments.
type Condition struct {
	Type string
	Arg1 string
	Arg2 string
	Arg3 string
	Arg4 string
}
